### ISSUE TITLE
나워 TODO

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#238]
related https://github.com/oleneyl/maplestory_dpm_calc/issues/237

- [x] 쉐도우 일루전이 단일 스킬 3개 합산으로 되어있음, 분리해야함
- [x] 쉐도우 스피어는 어둠 속성 공격에만 발동하는데, 본체 퀸터의 첫타는 어둠 속성이 아님
- [x] 쉐도우 스피어가 배트에 발동하는 로직이 빠져있음
  * 쉐도우 바이트에도 발동해야 할듯 싶음...아마도
- [x] 쉐도우 배트가 최대 5개 한도와 생성 딜레이 때문에 발생 확률이 0.333...보다 훨씬 낮음
  * 메익과 유사한 스킬로 변경해 해결할 예정
  * 도미니언의 지속 배트 생성도 한도에 막혀서 전혀 의미없음, 구현할 필요 없어보임

**Comment by icepeng** [comment]
배트는 생성 시점부터 생성 완료까지 960ms의 딜레이가 있음. 이 사이에는 퀸터를 써도 배트가 발사가 안됨. 일루전 + 익스텐드까지 썼을때 1퀸터의 사용횟수 판정은 10회. 0~960ms 사이에는 퀸터를 3번까지 쓸 수 있는데, 10개 중 5개의 배트가 증발함. 익스텐드만 있을 경우에는 사용판정 6회, 6개중 1개의 배트가 증발함.

**Comment by icepeng** [comment]
## 정확한 해결법

배트를 메익과 유사한 스킬로 만들고, 

### 장점

가장 정확함

### 단점

연산량이 꽤 늘어나서 느려지고, 만들기 피곤해짐.
코드 보는 다른 사람이 쉽게 이해하기 힘듬.
배트가 발동하는 쉐스 구현이 난해함.

2. 뭉개는 해결법

쉐도우 배트를 오라웨폰처럼 퀸터에 발동되는 스킬로 취급 (내부쿨 960ms)
이때, 익스텐드 ON/OFF를 나눠서 5타/4타로 나눠서 사용

### 장점

쉬움
배트가 발동하는 쉐스 구현하기가 그나마 편함

### 단점

부정확함
960ms의 딜레이동안 퀸터를 3번 쓰는게 아니라 정확히는 2.5번정도 쓰는것이기에 수치를 잘 끼워맞춰야함
=> 매직넘버가 되어버림

**Comment by icepeng** [comment]
#239 에서 일단 정확한 해결법으로 적용은 했으나, 퍼포먼스가 심히 떨어져 그대로 적용할지는 생각해봐야 합니다.
