### ISSUE TITLE
보마 TODO

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#240]
- [x] 사용 버프에 샤프, 일루젼 스텝이 빠져있음
- [x] 설명에 계산속도 향상을 위한 폭시 공속 3배 감소라 써져있는데 이제 아닌거같음
- [x] 피닉스, 이볼브 공격주기 확인해야함
- [x] 애로우 레인 타수 확인해야함, 허수아비에 줄기가 몇개까지 맞는 지 알아야함
- [x] 애로우 레인에 마법화살 발동 확률 2배 해야함
- [x] 잔영의 시 패시브 효과가 누락됨
- [x] 이볼브 종료시 피닉스 자동소환되므로 딜레이 0해도됨
- [x] ~플래터 설치 딜레이 120인지 600인지 확인할것~
- [x] 퀴버 풀버스트에 파이널 어택, 마법화살, 잔영의 시 반응하는지 확인해야함
- [x] 퀴버 풀버스트의 공퍼 증가량 잘못됨
- [x] 퀴버 풀버스트의 공격 주기 잘못됨

**Comment by icepeng** [comment]
잔영의 시는 매 소환당 2회*3타
애로우 레인에 파택 터지는것 확인됨
아머 피어싱 가동률 약 1/6
애로우 레인 줄기 안겹침, 5초당 3.5회 공격 -> 1회당 약 1440ms

**Comment by icepeng** [comment]
플래터 설치 딜레이는 일단 모른다고 표시해두고, 나중에 확실해지면 다시 적용

**Comment by icepeng** [comment]
애로우 레인, 잔영의 시(액티브)에는 파택/마법화살 모두 발동되는것 확인

**Comment by icepeng** [comment]
퀴버 풀버스트에 다 반응 안함

**Comment by cheese98** [comment]
https://old.reddit.com/r/Maplestory/comments/hya6yj/bowmasters_armor_break_1sec_minimum_cooldown_is/

당장 급한 이슈는 아니지만 아머 피어싱에 쿨감효과가 적용된다고 합니다. 나중에 쿨감모까지 구현 완료되면 다시 건드려야 할 것 같습니다.

**Comment by icepeng** [comment]
네, 코드 todo에 남겨두었습니다.

**Comment by icepeng** [comment]
지금 구현상 이미 적용이 가능합니다. 아머 피어싱을 쿨타임 9초의 버프로 해두었기 때문에... 나중에 red=True인 스킬에 쿨감모 적용도 되게만 하면 알아서 되겠네요.

**Comment by icepeng** [comment]
어........ 아니네요. 제대로 안될거 같습니다. 수정을 좀 해야겠네요.

**Comment by icepeng** [comment]
플래터 설치 딜레이 120ms 미만으로 측정됨
