### ISSUE TITLE
다크나이트 Checklist

### ISSUE THREAD

**Issue by icepeng** [oleneyl/maplestory_dpm_calc#242]
- [x] 패시브 효과
- [x] 버프 효과
- [x] 1~4차 딜레이
- [x] 1~4차 퍼뎀, 타수, 코강
- [x] 하이퍼 딜레이
- [x] 하이퍼 퍼뎀, 타수, 코강
- [x] 5차 딜레이
- [x] 5차 퍼뎀, 타수, 코강
- [x] 쿨감, 벞지 적용
- [x] 하이퍼 패시브 적용
- [x] 스킬간 연결 관계
- [x] 전투분석과 점유율 비교

**Comment by icepeng** [comment]
비홀더 쇼크의 딜레이 확인 필요

**Comment by icepeng** [comment]
비홀더 쇼크에 패시브로 강화되는 퍼뎀 빠져있음
궁그닐 디센트의 하이퍼 방무 곱적용인데 합적용으로 되는중

**Comment by icepeng** [comment]
피어스 사이클론 공격 횟수가 모자람
